import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='w-full relative'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-[80%] h-[70vh] mx-auto text-custom-grey text-center' style={{ "fontFamily": "logo" }}>
        Welcome to my portfolio site !
      </main>

    </div>
  )
}

export default Home
